database:
  user: postgres
  password: postgres
  #addr: 127.0.0.1:5432
  dbname: postgres
  params:
    disableTLS: true
    timezone: utc

server:
  address: 8081

userServer:
  address: 9091

debug: true

