database:
  user: postgres
  password: password
  addr: 127.0.0.1:5432
  dbname: bitsports
  params:
    disableTLS: true
    timezone: utc

server:
  address: 8080

userServer:
  address: 9090

debug: true
